adminRealm: "cnoe"
production: true
usePasswordFiles: false
proxyHeaders: "xforwarded"

image:
  registry: docker.io
  repository: bitnamilegacy/keycloak

global:
  defaultStorageClass: gp3
  security:
    allowInsecureImages: true

auth:
  adminUser: cnoe-admin
  adminPassword: cnoe-admin
  existingSecret: keycloak-config
  passwordSecretKey: KEYCLOAK_ADMIN_PASSWORD

ingress:
  enabled: true
  ingressClassName: nginx
  hostnameStrict: false
  servicePort: http
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
  extraHosts:
    - name: platform.vgurukool.com
      path: /keycloak/
  extraTls:
    - hosts:
        - vgurukool.com
      secretName: keycloak-server-tls
    - hosts:
        - platform.vgurukool.com
      secretName: keycloak-platform-tls
  tls: false

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
  auth:
    username: keycloak
    database: keycloak
    existingSecret: "keycloak-config"
    secretKeys:
      userPasswordKey: POSTGRES_PASSWORD
  architecture: standalone
