apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tla-lrs
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: tla-lrs
      repoURL: https://github.com/vgurukool/tla-helm/tree/main/charts/tla-lrs
      targetRevision: 0.0.1
      helm:
        releaseName: tla-lrs
        valueFiles:
          - $values/packages/tla-lrs/dev/values.yaml
        parameters: 
          - name: server.sso.issuer
            value: ${KEYCLOAK_CNOE_URL}
          - name: server.sso.redirectUrl
            value: ${ARGO_REDIRECT_URL}
    - repoURL: https://github.com/vgurukool/tla-idp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tla-lrs
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
